fragment File on UploadFileEntity {
  id
  attributes {
    name
    url
    fullUrl
    width
    height
    formats
    hash
    mime
    provider
    size
  }
}

fragment RouteItem on RouteEntity {
  id
  attributes {
    name
    slug
    order
  }
}

fragment ImageItem on ImageEntity {
  id
  attributes {
    name
    slug
    order
    routeCount
    file {
      data {
        ...File
      }
    }
  }
}

fragment Image on ImageEntity {
  id
  attributes {
    name
    slug
    order
    data
    routeCount
    file {
      data {
        ...File
      }
    }
  }
}

fragment SectorItem on SectorEntity {
  id
  attributes {
    name
    slug
    order
  }
}

fragment Sector on SectorEntity {
  id
  attributes {
    name
    slug
    order
    location {
      data {
        id
        attributes {
          name
          slug
        }
      }
    }
    images(sort: "order", pagination: { start: 0, limit: -1 }) {
      data {
        ...ImageItem
      }
    }
  }
}

fragment LocationItem on LocationEntity {
  id
  attributes {
    name
    slug
    order
  }
}

fragment Location on LocationEntity {
  id
  attributes {
    name
    slug
    order
    sectors(sort: "order", pagination: { start: 0, limit: -1 }) {
      data {
        ...SectorItem
      }
    }
  }
}
