fragment Grade on GradeEntity {
  id
  attributes {
    grade
    score
  }
}

fragment RouteItem on RouteEntity {
  id
  attributes {
    name
    slug
    order
    sitstart
    description
    grade {
      data {
        ...Grade
      }
    }
  }
}

fragment File on UploadFileEntity {
  id
  attributes {
    name
    url
    fullUrl
    width
    height
    formats
    hash
    mime
    provider
    size
  }
}

fragment ImageItem on ImageEntity {
  id
  attributes {
    name
    slug
    order
    routeCount
    file {
      data {
        ...File
      }
    }
  }
}

fragment Image on ImageEntity {
  id
  attributes {
    name
    slug
    order
    svg
    routeCount
    file {
      data {
        ...File
      }
    }
    routes(sort: "order", pagination: { start: 0, limit: -1 }) {
      data {
        ...RouteItem
      }
    }
    prevImage {
      data {
        ...PreloadImage
      }
    }
    nextImage {
      data {
        ...PreloadImage
      }
    }
  }
}

fragment PreloadImage on ImageEntity {
  id
  attributes {
    name
    slug
    order
    svg
    routeCount
    file {
      data {
        ...File
      }
    }
    routes(sort: "order", pagination: { start: 0, limit: -1 }) {
      data {
        ...RouteItem
      }
    }
  }
}
