fragment SectorItem on SectorEntity {
  id
  attributes {
    name
    slug
    order
  }
}

fragment Sector on SectorEntity {
  id
  attributes {
    name
    slug
    order
    location {
      data {
        id
        attributes {
          name
          slug
        }
      }
    }
    images(sort: "order", pagination: { start: 0, limit: -1 }) {
      data {
        ...ImageItem
      }
    }
  }
}
